spring:
#  mvc:
#    static-path-pattern: /**
  # 配置Mysql数据源
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/zxdb?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 配置redis
#  redis:
#    host: localhost
#    port: 6379
#    jedis:
#      pool:
#        min-idle: 5
#        max-idle: 10
#    connect-timeout: 1000
  profiles:
    # 开启 开发环境配置
    active: dev
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: on
  type-aliases-package: com.ch.pojo.entity

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
# 多种环境下 公共的配置 放在这里