spring:
  # 配置数据源
  datasource:
    username: chenk
    password: chenk
    url: jdbc:mysql://localhost:3307/halodb
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    # 关闭thymeleaf缓存
    cache: false
  profiles:
    # 开启 开发环境配置
    active: dev
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: on
  type-aliases-package: com.ch.pojo.entity

server:
  port: 8888
  servlet:
    context-path: /ch
# 公共的配置 放在这里