spring:
  # 配置数据源
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/eshop?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    # 关闭thymeleaf缓存
    cache: false
mybatis:
  mapper-locations: classpath:/mapper/*.xml

